name: "Software Verification Lab"
title: "Software Verification Lab at POSTECH"
description: "Software Verification Lab"

url: https://sv.postech.ac.kr
baseurl:
research_imgs: "/images/research"

footer:
  name:         "Software Verification Laboratory"
  department:   "Department of Computer Science and Engineering"
  affiliation1: "Pohang University of Science and Technology"
  affiliation2: "(POSTECH)"
  building1:    "Engineering Building 2"
  building2:    "Room 204"
  address1:     "77 Cheongam-ro, Nam-gu"
  address2:     "Pohang-si, Gyeongsangbuk-do"
  address3:     "37673, Republic of Korea"
  copyright_year: 2026
  privacy_policy_url: "https://www.postech.ac.kr/kor/usage-guide/privacy_policy.do"

markdown: kramdown
highlighter: rouge

nav:
  - name: "publications"
    href: "/publications"
  - name: "members"
    href: "/members"
  - name: "research"
    href: "/research"

include:
  - _pages

sass:
  style: :compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

collections:
  researchtopics:
    output: true
    permalink: /research/:title.html
