# Basic
name: "Software Verification Lab"
title: "Software Verification Lab at POSTECH"
description: "Software Verification Lab"

# URL
url: https://sv.postech.ac.kr
baseurl:
research_imgs: "/images/research"

# Footer
footer:
  name: "Software Verification Laboratory"
  affiliation: "E2 Room 204, Dept. of CSE, POSTECH"
  address: "77 Cheongam-ro, Nam-gu, Pohang-si, Gyeongsangbuk-do, 37673, Republic of Korea"
  copyright_year: 2026
  privacy_policy_url: "https://www.postech.ac.kr/kor/usage-guide/privacy_policy.do"

# Markdown
markdown: kramdown

# Highlighter
highlighter: rouge

# Navigation
nav:
  - name: "publications"
    href: "/publications"
  - name: "members"
    href: "/members"
  - name: "research"
    href: "/research"

# Include _pages/ in build (underscore dirs are excluded by default)
include:
  - _pages

# Sass
sass:
  style: :compressed

# Scopes
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

collections:
  research:
    output: true
  researchtopics:
    output: true
    permalink: /research/:title.html
  home:
    output: true
